### ISSUE TITLE
14.02. Add song.

### ISSUE THREAD

**Issue by LucasDondo** [LucasDondo/python_crash_course#27]
Could be [Spark Mandriller Stage](https://open.spotify.com/track/5r4lsErOFkd8VO7m7Dg7Gt?si=783cf58b30674ec9) or [Arrow's soundtrack](https://open.spotify.com/album/0Hsit07149488kiRI1UiaJ?si=5c1e695f380e4858), but because of _copyright_ I'll use [Arrow](https://open.spotify.com/track/5kKDRy6ihOSKxpjglJsrKh?si=55158c849791413c) by [Jim Yosef](https://open.spotify.com/artist/40HDiLfKm0tXk2FxlJx6aO?si=BCsYQxIURBunqX0NNUlVQw).
# ToDos
- [x] Fade in the music when game turns active.
- [x] Fade out the music when the user losses.
- [x] Fade in, fade out and rewind while no game is active.
